import Link from "next/link";

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-10">
      <h2 className="font-display text-xl font-bold text-foreground">{title}</h2>
      <div className="mt-3 flex flex-col gap-3 text-sm leading-7 text-muted">{children}</div>
    </section>
  );
}

export default function DisclaimerPage() {
  return (
    <div className="flex flex-1 flex-col bg-background">
      <div className="mx-auto w-full max-w-3xl px-6 py-16 sm:py-24">
        <span className="rounded-full border border-caution/30 bg-caution-soft px-4 py-1.5 text-xs font-semibold uppercase tracking-widest text-caution">
          Please read
        </span>
        <h1 className="mt-6 font-display text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
          Health &amp; Supplement Disclaimer
        </h1>
        <p className="mt-3 text-sm text-muted-2">Effective date: August 22, 2026</p>

        <p className="mt-8 text-sm leading-7 text-muted">
          This page explains the limits of what True U Athletics — including the quiz, your
          supplement stack, and the Coach AI assistant (together, the &quot;Service&quot;) —
          can tell you. It is part of our{" "}
          <Link href="/terms" className="text-accent hover:underline">
            Terms of Service
          </Link>
          . Please read it before following any recommendation from the Service.
        </p>

        <Section title="Not Medical Advice">
          <p>
            True U Athletics is an educational tool. Nothing on this Service is, or is intended to
            be, medical advice, a diagnosis, or a treatment plan. The people behind True U
            Athletics are athletes and coaches, not physicians, registered dietitians, or licensed
            healthcare providers, and using the Service does not create a doctor-patient or any
            other professional relationship.
          </p>
        </Section>

        <Section title="FDA Disclosure">
          <p>
            Statements made by True U Athletics, including anything generated by Coach, have not
            been evaluated by the Food and Drug Administration. Dietary supplements discussed or
            recommended through the Service are not intended to diagnose, treat, cure, or prevent
            any disease.
          </p>
        </Section>

        <Section title="Talk to a Doctor First">
          <p>
            Always consult a physician, pharmacist, or other qualified healthcare provider before
            starting any new supplement, especially if you:
          </p>
          <ul className="list-disc space-y-1 pl-5">
            <li>are pregnant, trying to become pregnant, or nursing;</li>
            <li>are under 18 (the quiz will not generate recommendations for you, by design);</li>
            <li>take any prescription or over-the-counter medication;</li>
            <li>have any diagnosed medical condition; or</li>
            <li>have previously had an adverse reaction to a supplement or medication.</li>
          </ul>
          <p>
            Our quiz asks only whether you take medication or manage a condition (yes/no) so we can
            steer you toward general wellness ingredients and away from stacking concerns — it
            cannot account for your specific medication, dosage, or diagnosis the way a doctor or
            pharmacist can.
          </p>
        </Section>

        <Section title="Coach Is AI-Generated">
          <p>
            Coach&apos;s answers are generated automatically by a third-party AI model, not written
            or reviewed by a medical professional or dietitian before you see them. AI-generated
            answers can be incomplete, out of date, or simply wrong. Treat Coach as a
            starting point for questions to bring to a real professional — not as a final answer.
          </p>
        </Section>

        <Section title="Individual Results Vary">
          <p>
            Supplement recommendations are based on general patterns in sports nutrition research
            and the information you provide in the quiz. They are not personalized medical
            guidance, and we make no guarantee about the effects, benefits, or safety of any
            supplement for your individual body, training, or health history.
          </p>
        </Section>

        <Section title="Third-Party Products">
          <p>
            If the Service links to or names specific supplement products, brands, or retailers,
            we are not responsible for the manufacturing, labeling, quality, or safety of those
            products. Always read product labels and follow manufacturer dosing instructions.
          </p>
        </Section>

        <Section title="Questions">
          <p>
            If anything on this page is unclear, or you have questions about a recommendation you
            received, email{" "}
            <a href="mailto:team@trueusupplements.com" className="text-accent hover:underline">
              team@trueusupplements.com
            </a>{" "}
            — but for anything about your personal health, please talk to a doctor first.
          </p>
        </Section>
      </div>
    </div>
  );
}
